package de.johannes.cnc;

import org.w3c.dom.*;
import javax.xml.parsers.*;
import java.io.*;
import java.util.*;

public class SvgToGcode {

    private double feedRate    = 1000;
    private int    bezierSteps = 20;
    private double safeZ       = 5.0;
    private double cutZ        = 0.0;
    private double pxToMm      = 25.4 / 96.0;

    public void setFeedRate(double feedRate)      { this.feedRate = feedRate; }
    public void setBezierSteps(int bezierSteps)   { this.bezierSteps = bezierSteps; }
    public void setSafeZ(double safeZ)            { this.safeZ = safeZ; }
    public void setCutZ(double cutZ)              { this.cutZ = cutZ; }
    public void setPxToMm(double pxToMm)          { this.pxToMm = pxToMm; }

    public SvgToGcode() {
    }

    public String convert(String svg) throws Exception {
        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setNamespaceAware(true);
        DocumentBuilder builder = factory.newDocumentBuilder();
        Document doc = builder.parse(new ByteArrayInputStream(svg.getBytes(java.nio.charset.StandardCharsets.UTF_8)));
        doc.getDocumentElement().normalize();

        Element root = doc.getDocumentElement();
        String widthAttr   = root.getAttribute("width");
        String viewBoxAttr = root.getAttribute("viewBox");
        if (widthAttr != null && !widthAttr.isBlank() && !viewBoxAttr.isBlank()) {
            double[] vb = parseNumbers(viewBoxAttr);
            if (vb.length >= 3 && vb[2] > 0) {
                String w = widthAttr.trim().toLowerCase();
                double widthMm;
                if      (w.endsWith("mm")) widthMm = Double.parseDouble(w.replace("mm", "").trim());
                else if (w.endsWith("cm")) widthMm = Double.parseDouble(w.replace("cm", "").trim()) * 10.0;
                else if (w.endsWith("in")) widthMm = Double.parseDouble(w.replace("in", "").trim()) * 25.4;
                else if (w.endsWith("px")) widthMm = Double.parseDouble(w.replace("px", "").trim()) * (25.4 / 96.0);
                else                       widthMm = Double.parseDouble(w.replaceAll("[^0-9.]", "")) * (25.4 / 96.0);
                pxToMm = widthMm / vb[2];
            }
        }

        double svgHeight = parseSvgHeight(doc.getDocumentElement());

        StringBuilder gcode = new StringBuilder();
        gcode.append("; Generated by SvgToGcode\n");
        gcode.append("G21 ; mm\n");
        gcode.append("G90 ; absolute\n");
        gcode.append(String.format(Locale.US, "G0 Z%.3f ; lift\n", safeZ));

        traverseNode(doc.getDocumentElement(), new double[]{1,0,0,1,0,0}, svgHeight, gcode);

        gcode.append(String.format(Locale.US, "G0 Z%.3f ; lift at end\n", safeZ));
        gcode.append("G0 X0 Y0 ; home\n");

        return gcode.toString();
    }

    private void traverseNode(Node node, double[] parentTransform, double svgHeight, StringBuilder gcode) {
        if (node.getNodeType() != Node.ELEMENT_NODE) return;
        Element el = (Element) node;

        double[] transform = multiplyMatrix(parentTransform, parseTransform(el.getAttribute("transform")));

        String tag = el.getLocalName() == null ? el.getNodeName() : el.getLocalName();

        switch (tag.toLowerCase()) {
            case "path"     -> handlePath(el.getAttribute("d"), transform, svgHeight, gcode);
            case "line"     -> handleLine(el, transform, svgHeight, gcode);
            case "rect"     -> handleRect(el, transform, svgHeight, gcode);
            case "circle"   -> handleCircle(el, transform, svgHeight, gcode);
            case "ellipse"  -> handleEllipse(el, transform, svgHeight, gcode);
            case "polyline" -> handlePolyline(el.getAttribute("points"), transform, svgHeight, false, gcode);
            case "polygon"  -> handlePolyline(el.getAttribute("points"), transform, svgHeight, true, gcode);
        }

        NodeList children = node.getChildNodes();
        for (int i = 0; i < children.getLength(); i++) {
            traverseNode(children.item(i), transform, svgHeight, gcode);
        }
    }

    private void handleLine(Element el, double[] t, double svgHeight, StringBuilder gcode) {
        double x1 = d(el, "x1"), y1 = d(el, "y1");
        double x2 = d(el, "x2"), y2 = d(el, "y2");
        List<double[]> pts = List.of(new double[]{x1,y1}, new double[]{x2,y2});
        emitPolyline(pts, false, t, svgHeight, gcode);
    }

    private void handleRect(Element el, double[] t, double svgHeight, StringBuilder gcode) {
        double x = d(el,"x"), y = d(el,"y"), w = d(el,"width"), h = d(el,"height");
        List<double[]> pts = List.of(
                new double[]{x,   y  },
                new double[]{x+w, y  },
                new double[]{x+w, y+h},
                new double[]{x,   y+h}
        );
        emitPolyline(pts, true, t, svgHeight, gcode);
    }

    private void handleCircle(Element el, double[] t, double svgHeight, StringBuilder gcode) {
        double cx = d(el,"cx"), cy = d(el,"cy"), r = d(el,"r");
        emitEllipse(cx, cy, r, r, t, svgHeight, gcode);
    }

    private void handleEllipse(Element el, double[] t, double svgHeight, StringBuilder gcode) {
        double cx = d(el,"cx"), cy = d(el,"cy"), rx = d(el,"rx"), ry = d(el,"ry");
        emitEllipse(cx, cy, rx, ry, t, svgHeight, gcode);
    }

    private void emitEllipse(double cx, double cy, double rx, double ry,
                             double[] t, double svgHeight, StringBuilder gcode) {
        int steps = Math.max(bezierSteps * 4, 64);
        List<double[]> pts = new ArrayList<>();
        for (int i = 0; i <= steps; i++) {
            double angle = 2 * Math.PI * i / steps;
            pts.add(new double[]{ cx + rx * Math.cos(angle), cy + ry * Math.sin(angle) });
        }
        emitPolyline(pts, false, t, svgHeight, gcode);
    }

    private void handlePolyline(String pointsAttr, double[] t, double svgHeight, boolean close, StringBuilder gcode) {
        List<double[]> pts = new ArrayList<>();
        String[] tokens = pointsAttr.trim().split("[\\s,]+");
        for (int i = 0; i + 1 < tokens.length; i += 2) {
            pts.add(new double[]{ Double.parseDouble(tokens[i]), Double.parseDouble(tokens[i+1]) });
        }
        emitPolyline(pts, close, t, svgHeight, gcode);
    }

    private void handlePath(String d, double[] t, double svgHeight, StringBuilder gcode) {
        if (d == null || d.isBlank()) return;

        List<double[]> currentContour = new ArrayList<>();
        double cx = 0, cy = 0;
        double sx = 0, sy = 0;
        double prevCpX = 0, prevCpY = 0;
        char prevCmd = ' ';

        List<String> tokens = tokenizePath(d);
        int i = 0;

        while (i < tokens.size()) {
            char cmd = tokens.get(i).charAt(0);
            boolean rel = Character.isLowerCase(cmd);
            cmd = Character.toUpperCase(cmd);
            i++;

            do {
                switch (cmd) {
                    case 'M' -> {
                        if (!currentContour.isEmpty()) {
                            emitPolyline(currentContour, false, t, svgHeight, gcode);
                            currentContour = new ArrayList<>();
                        }
                        double[] args = nextArgs(tokens, i, 2); i += 2;
                        cx = rel ? cx + args[0] : args[0];
                        cy = rel ? cy + args[1] : args[1];
                        sx = cx; sy = cy;
                        currentContour.add(new double[]{cx, cy});
                        cmd = rel ? 'l' : 'L';
                        rel = Character.isLowerCase(cmd);
                        cmd = 'L';
                    }
                    case 'L' -> {
                        double[] args = nextArgs(tokens, i, 2); i += 2;
                        cx = rel ? cx + args[0] : args[0];
                        cy = rel ? cy + args[1] : args[1];
                        currentContour.add(new double[]{cx, cy});
                    }
                    case 'H' -> {
                        double[] args = nextArgs(tokens, i, 1); i += 1;
                        cx = rel ? cx + args[0] : args[0];
                        currentContour.add(new double[]{cx, cy});
                    }
                    case 'V' -> {
                        double[] args = nextArgs(tokens, i, 1); i += 1;
                        cy = rel ? cy + args[0] : args[0];
                        currentContour.add(new double[]{cx, cy});
                    }
                    case 'C' -> {
                        double[] args = nextArgs(tokens, i, 6); i += 6;
                        double x1 = rel ? cx+args[0] : args[0], y1 = rel ? cy+args[1] : args[1];
                        double x2 = rel ? cx+args[2] : args[2], y2 = rel ? cy+args[3] : args[3];
                        double  x = rel ? cx+args[4] : args[4],  y = rel ? cy+args[5] : args[5];
                        addCubicBezier(currentContour, cx, cy, x1, y1, x2, y2, x, y);
                        prevCpX = x2; prevCpY = y2;
                        cx = x; cy = y;
                    }
                    case 'S' -> {
                        double[] args = nextArgs(tokens, i, 4); i += 4;
                        double x1 = (prevCmd=='C'||prevCmd=='S') ? 2*cx - prevCpX : cx;
                        double y1 = (prevCmd=='C'||prevCmd=='S') ? 2*cy - prevCpY : cy;
                        double x2 = rel ? cx+args[0] : args[0], y2 = rel ? cy+args[1] : args[1];
                        double  x = rel ? cx+args[2] : args[2],  y = rel ? cy+args[3] : args[3];
                        addCubicBezier(currentContour, cx, cy, x1, y1, x2, y2, x, y);
                        prevCpX = x2; prevCpY = y2;
                        cx = x; cy = y;
                    }
                    case 'Q' -> {
                        double[] args = nextArgs(tokens, i, 4); i += 4;
                        double x1 = rel ? cx+args[0] : args[0], y1 = rel ? cy+args[1] : args[1];
                        double  x = rel ? cx+args[2] : args[2],  y = rel ? cy+args[3] : args[3];
                        addQuadBezier(currentContour, cx, cy, x1, y1, x, y);
                        prevCpX = x1; prevCpY = y1;
                        cx = x; cy = y;
                    }
                    case 'T' -> {
                        double[] args = nextArgs(tokens, i, 2); i += 2;
                        double x1 = (prevCmd=='Q'||prevCmd=='T') ? 2*cx - prevCpX : cx;
                        double y1 = (prevCmd=='Q'||prevCmd=='T') ? 2*cy - prevCpY : cy;
                        double  x = rel ? cx+args[0] : args[0],  y = rel ? cy+args[1] : args[1];
                        addQuadBezier(currentContour, cx, cy, x1, y1, x, y);
                        prevCpX = x1; prevCpY = y1;
                        cx = x; cy = y;
                    }
                    case 'A' -> {
                        double[] args = nextArgs(tokens, i, 7); i += 7;
                        double rx = args[0], ry = args[1], xRot = args[2];
                        boolean largeArc = args[3] != 0, sweep = args[4] != 0;
                        double ex = rel ? cx+args[5] : args[5], ey = rel ? cy+args[6] : args[6];
                        addArc(currentContour, cx, cy, rx, ry, xRot, largeArc, sweep, ex, ey);
                        cx = ex; cy = ey;
                    }
                    case 'Z' -> {
                        currentContour.add(new double[]{sx, sy});
                        emitPolyline(currentContour, false, t, svgHeight, gcode);
                        currentContour = new ArrayList<>();
                        cx = sx; cy = sy;
                    }
                    default -> { /* skip unknown */ }
                }

                prevCmd = cmd;

            } while (i < tokens.size() && !tokens.get(i).matches("[a-zA-Z]"));
        }

        if (!currentContour.isEmpty()) {
            emitPolyline(currentContour, false, t, svgHeight, gcode);
        }
    }

    private void addCubicBezier(List<double[]> pts,
                                double x0, double y0, double x1, double y1,
                                double x2, double y2, double x3, double y3) {
        for (int i = 1; i <= bezierSteps; i++) {
            double t = (double) i / bezierSteps;
            double u = 1 - t;
            double x = u*u*u*x0 + 3*u*u*t*x1 + 3*u*t*t*x2 + t*t*t*x3;
            double y = u*u*u*y0 + 3*u*u*t*y1 + 3*u*t*t*y2 + t*t*t*y3;
            pts.add(new double[]{x, y});
        }
    }

    private void addQuadBezier(List<double[]> pts,
                               double x0, double y0, double x1, double y1,
                               double x2, double y2) {
        for (int i = 1; i <= bezierSteps; i++) {
            double t = (double) i / bezierSteps;
            double u = 1 - t;
            double x = u*u*x0 + 2*u*t*x1 + t*t*x2;
            double y = u*u*y0 + 2*u*t*y1 + t*t*y2;
            pts.add(new double[]{x, y});
        }
    }

    private void addArc(List<double[]> pts,
                        double x1, double y1, double rx, double ry,
                        double xRotDeg, boolean largeArc, boolean sweep,
                        double x2, double y2) {
        if (rx == 0 || ry == 0) { pts.add(new double[]{x2,y2}); return; }
        double phi = Math.toRadians(xRotDeg);
        double cosPhi = Math.cos(phi), sinPhi = Math.sin(phi);
        double dx = (x1-x2)/2, dy = (y1-y2)/2;
        double x1p =  cosPhi*dx + sinPhi*dy;
        double y1p = -sinPhi*dx + cosPhi*dy;
        rx = Math.abs(rx); ry = Math.abs(ry);
        double lambda = (x1p*x1p)/(rx*rx) + (y1p*y1p)/(ry*ry);
        if (lambda > 1) { rx *= Math.sqrt(lambda); ry *= Math.sqrt(lambda); }
        double num = (rx*rx*ry*ry) - (rx*rx*y1p*y1p) - (ry*ry*x1p*x1p);
        double den = (rx*rx*y1p*y1p) + (ry*ry*x1p*x1p);
        double sq = Math.max(0, num/den);
        double coef = (largeArc == sweep ? -1 : 1) * Math.sqrt(sq);
        double cxp =  coef * rx*y1p/ry;
        double cyp = -coef * ry*x1p/rx;
        double cx  = cosPhi*cxp - sinPhi*cyp + (x1+x2)/2;
        double cy  = sinPhi*cxp + cosPhi*cyp + (y1+y2)/2;
        double ux = (x1p-cxp)/rx, uy = (y1p-cyp)/ry;
        double vx = (-x1p-cxp)/rx, vy = (-y1p-cyp)/ry;
        double startAngle = angle(1,0,ux,uy);
        double dAngle     = angle(ux,uy,vx,vy);
        if (!sweep && dAngle > 0) dAngle -= 2*Math.PI;
        if ( sweep && dAngle < 0) dAngle += 2*Math.PI;
        int steps = Math.max(bezierSteps, (int)(Math.abs(dAngle) * Math.max(rx,ry) / 0.5));
        for (int i = 1; i <= steps; i++) {
            double t = (double) i / steps;
            double a = startAngle + dAngle * t;
            double xp = cosPhi * rx*Math.cos(a) - sinPhi * ry*Math.sin(a) + cx;
            double yp = sinPhi * rx*Math.cos(a) + cosPhi * ry*Math.sin(a) + cy;
            pts.add(new double[]{xp, yp});
        }
    }

    private double angle(double ux, double uy, double vx, double vy) {
        double dot = ux*vx + uy*vy;
        double len = Math.sqrt((ux*ux+uy*uy)*(vx*vx+vy*vy));
        double a = Math.acos(Math.max(-1, Math.min(1, dot/len)));
        return (ux*vy - uy*vx < 0) ? -a : a;
    }

    private void emitPolyline(List<double[]> pts, boolean close,
                              double[] t, double svgHeight, StringBuilder gcode) {
        if (pts.isEmpty()) return;

        double[] first = applyTransform(pts.get(0), t, svgHeight);
        gcode.append(String.format(Locale.US, "G0 X%.3f Y%.3f\n", first[0], first[1]));
        gcode.append(String.format(Locale.US, "G0 Z%.3f\n", cutZ));

        for (int i = 1; i < pts.size(); i++) {
            double[] p = applyTransform(pts.get(i), t, svgHeight);
            gcode.append(String.format(Locale.US, "G1 X%.3f Y%.3f F%.0f\n", p[0], p[1], feedRate));
        }

        if (close) {
            gcode.append(String.format(Locale.US, "G1 X%.3f Y%.3f F%.0f\n", first[0], first[1], feedRate));
        }

        gcode.append(String.format(Locale.US, "G0 Z%.3f\n", safeZ));
    }

    private double[] applyTransform(double[] pt, double[] m, double svgHeight) {
        double x = m[0]*pt[0] + m[2]*pt[1] + m[4];
        double y = m[1]*pt[0] + m[3]*pt[1] + m[5];
        return new double[]{ x * pxToMm, (svgHeight - y) * pxToMm };
    }

    private double[] parseTransform(String attr) {
        double[] m = {1,0,0,1,0,0};
        if (attr == null || attr.isBlank()) return m;

        java.util.regex.Matcher mat = java.util.regex.Pattern
                .compile("(matrix|translate|scale|rotate|skewX|skewY)\\(([^)]+)\\)")
                .matcher(attr);

        while (mat.find()) {
            String type = mat.group(1);
            double[] a = parseNumbers(mat.group(2));
            double[] n = switch (type) {
                case "matrix"    -> new double[]{ a[0],a[1],a[2],a[3],a[4],a[5] };
                case "translate" -> new double[]{ 1,0,0,1, a[0], a.length>1?a[1]:0 };
                case "scale"     -> new double[]{ a[0],0,0, a.length>1?a[1]:a[0], 0,0 };
                case "rotate"    -> {
                    double r = Math.toRadians(a[0]);
                    double cos = Math.cos(r), sin = Math.sin(r);
                    if (a.length > 2) {
                        double tx = a[1] - cos*a[1] + sin*a[2];
                        double ty = a[2] - sin*a[1] - cos*a[2];
                        yield new double[]{ cos, sin, -sin, cos, tx, ty };
                    }
                    yield new double[]{ cos, sin, -sin, cos, 0, 0 };
                }
                case "skewX" -> { double t2 = Math.tan(Math.toRadians(a[0])); yield new double[]{1,0,t2,1,0,0}; }
                case "skewY" -> { double t2 = Math.tan(Math.toRadians(a[0])); yield new double[]{1,t2,0,1,0,0}; }
                default      -> new double[]{ 1,0,0,1,0,0 };
            };
            m = multiplyMatrix(m, n);
        }
        return m;
    }

    private double[] multiplyMatrix(double[] a, double[] b) {
        return new double[]{
                a[0]*b[0] + a[2]*b[1],
                a[1]*b[0] + a[3]*b[1],
                a[0]*b[2] + a[2]*b[3],
                a[1]*b[2] + a[3]*b[3],
                a[0]*b[4] + a[2]*b[5] + a[4],
                a[1]*b[4] + a[3]*b[5] + a[5]
        };
    }

    private double parseSvgHeight(Element svg) {
        String vb = svg.getAttribute("viewBox");
        if (vb != null && !vb.isBlank()) {
            double[] v = parseNumbers(vb);
            if (v.length >= 4) return v[3];
        }
        String h = svg.getAttribute("height");
        if (h != null && !h.isBlank()) {
            try { return Double.parseDouble(h.replaceAll("[^0-9.]", "")); }
            catch (Exception ignored) {}
        }
        return 744;
    }

    private double d(Element el, String attr) {
        String v = el.getAttribute(attr);
        if (v == null || v.isBlank()) return 0;
        try { return Double.parseDouble(v.trim()); } catch (Exception e) { return 0; }
    }

    private double[] parseNumbers(String s) {
        String[] parts = s.trim().split("[\\s,]+");
        double[] nums = new double[parts.length];
        for (int i = 0; i < parts.length; i++) {
            try { nums[i] = Double.parseDouble(parts[i]); } catch (Exception e) { nums[i] = 0; }
        }
        return nums;
    }

    private List<String> tokenizePath(String d) {
        List<String> tokens = new ArrayList<>();
        java.util.regex.Matcher m = java.util.regex.Pattern
                .compile("[a-zA-Z]|[-+]?[0-9]*\\.?[0-9]+(?:[eE][-+]?[0-9]+)?")
                .matcher(d);
        while (m.find()) tokens.add(m.group());
        return tokens;
    }

    private double[] nextArgs(List<String> tokens, int i, int count) {
        double[] args = new double[count];
        for (int j = 0; j < count && i+j < tokens.size(); j++) {
            try { args[j] = Double.parseDouble(tokens.get(i+j)); } catch (Exception e) { args[j] = 0; }
        }
        return args;
    }
}